apiVersion: v1
kind: ServiceAccount
metadata:
  name: synology-updater-sa
  namespace: cert-manager

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: synology-updater-role
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "issuers", "clusterissuers"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: synology-updater-rolebinding
subjects:
  - kind: ServiceAccount
    name: synology-updater-sa
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: synology-updater-role
  apiGroup: rbac.authorization.k8s.io